[2022-11-18T04:32:57.424+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_operator.spark-job manual__2022-11-18T04:32:34.560494+00:00 [queued]>
[2022-11-18T04:32:57.432+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_operator.spark-job manual__2022-11-18T04:32:34.560494+00:00 [queued]>
[2022-11-18T04:32:57.433+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T04:32:57.435+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T04:32:57.435+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T04:32:57.449+0000] {taskinstance.py:1383} INFO - Executing <Task(SparkSubmitOperator): spark-job> on 2022-11-18 04:32:34.560494+00:00
[2022-11-18T04:32:57.455+0000] {standard_task_runner.py:55} INFO - Started process 333 to run task
[2022-11-18T04:32:57.455+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-11-18T04:32:57.460+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_operator', 'spark-job', 'manual__2022-11-18T04:32:34.560494+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/load_data_to_spark.py', '--cfg-path', '/tmp/tmp1n2tqbdt']
[2022-11-18T04:32:57.461+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask spark-job
[2022-11-18T04:32:57.500+0000] {task_command.py:376} INFO - Running <TaskInstance: spark_operator.spark-job manual__2022-11-18T04:32:34.560494+00:00 [running]> on host 69dc550e7316
[2022-11-18T04:32:57.546+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_operator
AIRFLOW_CTX_TASK_ID=spark-job
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T04:32:34.560494+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T04:32:34.560494+00:00
[2022-11-18T04:32:57.553+0000] {base.py:71} INFO - Using connection ID 'spark_local' for task execution.
[2022-11-18T04:32:57.554+0000] {spark_submit.py:334} INFO - Spark-Submit cmd: spark-submit --master spark://Posathorns-MacBook-Pro-4.local:7077 --name arrow-spark json_to_spark.py
[2022-11-18T04:32:57.572+0000] {spark_submit.py:485} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2022-11-18T04:32:57.939+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-11-18T04:32:57.943+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-11-18T04:32:57.944+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/clientserver.py", line 507, in send_command
    "Error while sending", e, proto.ERROR_ON_SEND)
py4j.protocol.Py4JNetworkError: Error while sending
[2022-11-18T04:32:57.947+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-11-18T04:33:01.149+0000] {spark_submit.py:485} INFO - /usr/local/bin/python: can't open file '/opt/***/json_to_spark.py': [Errno 2] No such file or directory
[2022-11-18T04:33:01.173+0000] {spark_submit.py:485} INFO - 22/11/18 04:33:01 INFO ShutdownHookManager: Shutdown hook called
[2022-11-18T04:33:01.180+0000] {spark_submit.py:485} INFO - 22/11/18 04:33:01 INFO ShutdownHookManager: Deleting directory /tmp/spark-37c3bfe7-311b-4839-a948-2b1dfab638bc
[2022-11-18T04:33:01.221+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://Posathorns-MacBook-Pro-4.local:7077 --name arrow-spark json_to_spark.py. Error code is: 2.
[2022-11-18T04:33:01.226+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=spark_operator, task_id=spark-job, execution_date=20221118T043234, start_date=20221118T043257, end_date=20221118T043301
[2022-11-18T04:33:01.237+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 37 for task spark-job (Cannot execute: spark-submit --master spark://Posathorns-MacBook-Pro-4.local:7077 --name arrow-spark json_to_spark.py. Error code is: 2.; 333)
[2022-11-18T04:33:01.249+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T04:33:01.262+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
